baseURL = 'https://nikolai.kim/'
languageCode = 'en-us'
title = 'Nikolai Kim'
theme = 'paper'
copyright = 'CC0-1.0'

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts'
  weight = 10
[[menu.main]]
  identifier = 'projects'
  name = 'Projects'
  url = '/pages/projects'
  weight = 15
[[menu.main]]
  identifier = 'license'
  name = 'License'
  url = '/pages/license'
  weight = 20
[[menu.main]]
  identifier = 'keys'
  name = 'Public Key'
  url = '/pages/keys'
  weight = 30
[[menu.main]]
  identifier = 'ru'
  name = 'По-русски'
  url = 'https://nikolai.pp.ru/'
  weight = 40

[permalinks]
  'posts' = '/posts/:slug'

[params]
  github = 'object-required'
